#include "arduino_secrets.h"
// Arduino_MKRENV - Version: Latest 

/* 
  Sketch generated by the Arduino IoT Cloud Thing "MKR_ENV_Shield"
  https://create.arduino.cc/cloud/things/66e3f987-d111-4a56-9644-205e97149ebf 
  edited by Michelle Howie Nov 2020

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing properties

  float lux;
  CloudRelativeHumidity humidity;
  float temperature;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
  
  Simple Environmental Monitor Materials:
  + Arduino MKR NB 1500
  + Arduino MKR ENV Shield
  
*/

#include <Arduino_MKRENV.h>
#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  // Initialize ENV Shield
 ENV.begin();
}

void loop() {
  ArduinoCloud.update();
  
    temperature = ENV.readTemperature();
   humidity    = ENV.readHumidity();
   lux         = ENV.readIlluminance();
  
}








