// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]      = "66e3f987-d111-4a56-9644-205e97149ebf";

const char GPRS_APN[]      = SECRET_OPTIONAL_APN;
const char PINNUMBER[]     = SECRET_OPTIONAL_PIN;
const char GPRS_LOGIN[]    = SECRET_OPTIONAL_USERNAME;
const char GPRS_PASSWORD[] = SECRET_OPTIONAL_PASSWORD;


float lux;
CloudRelativeHumidity humidity;
float temperature;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(lux, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(humidity, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperature, READ, 60 * SECONDS, NULL);

}

NBConnectionHandler ArduinoIoTPreferredConnection(PINNUMBER, GPRS_APN, GPRS_LOGIN, GPRS_PASSWORD);